version: 1.0.{build}
image:
- Visual Studio 2013
before_build:
  - cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86

- Visual Studio 2015
before_build:
  - cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

- Visual Studio 2017
before_build:
  - cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio 15.0\VC\vcvarsall.bat" x86

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      DIA_PATH: "C:/Program Files (x86)/Microsoft Visual Studio 12.0/DIA SDK/include"
      ATL_PATH: "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/atlmfc/include"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      DIA_PATH: "C:/Program Files (x86)/Microsoft Visual Studio 14.0/DIA SDK/include"
      ATL_PATH: "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      DIA_PATH: "C:/Program Files (x86)/Microsoft Visual Studio 15.0/DIA SDK/include"
      ATL_PATH: "C:/Program Files (x86)/Microsoft Visual Studio 15.0/VC/atlmfc/include"

clone_folder: c:\breakpad

build_script:
- cmd: >-
    mkdir build
    cd build
    cmake -DCMAKE_PREFIX_PATH="%DIA_PATH%;%ATL_PATH%" ../
    cmake --build . --target ALL_BUILD --config RelWithDebInfo
